### ISSUE TITLE
Get the database running again

### ISSUE THREAD

**Issue by pp23** [iljabauer/quamo-wiki#33]
We are still trying to get database running again. We have moved the META-INF directory to several places and nothing have worked: Always the same error: 

<code>
javax.persistence.PersistenceException: No Persistence provider for EntityManager named Service
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:69)
    at de.devboost.quamo.db.dao.QuamoDAOBase.configure(QuamoDAOBase.java:122)
    at de.devboost.quamo.db.dao.QuamoDAOBase.configure(QuamoDAOBase.java:117)
    at de.devboost.quamo.db.dao.QuamoDAOBase.getEntityManagerFactory(QuamoDAOBase.java:136)
    at de.devboost.quamo.db.dao.QuamoDAOBase.createEntityManager(QuamoDAOBase.java:156)
    at de.devboost.quamo.db.dao.QuamoDAOBase.executeInTransaction(QuamoDAOBase.java:363)
    at de.devboost.quamo.db.dao.QuamoDAOBase.executeInTransaction(QuamoDAOBase.java:349)
    at de.devboost.quamo.db.dao.QuamoDAOBase.executeInTransaction(QuamoDAOBase.java:340)
    at de.devboost.quamo.db.dao.QuamoDAOBase.executeInTransaction(QuamoDAOBase.java:332)
    at de.devboost.quamo.db.dao.QuamoDAOBase.countErrorTypes(QuamoDAOBase.java:1874)
    at de.devboost.quamo.db.test.ErrorTypeTest.testCreateAndCount(ErrorTypeTest.java:63)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</code>

Even the HEDL-tests in the package quamo.db do not work. Can you imagine where the problem is?

**Comment by iljabauer** [comment]
Why do you move the META-INF folder? I will try to fix the problem

**Comment by iljabauer** [comment]
Another thing that I see is, that you not run your database queries in a transaction

**Comment by iljabauer** [comment]
This is also not possible, because IMetricMapable is not an entity type.
de.devboost.quamo.db.IMetricMapable referenceEntity;

If you want to implements a kind of abstraction, just use HEDL abstract classes or normal entities.

**Comment by iljabauer** [comment]
I committed a version which is working for me. I recommend you following things:
- Create a new Workspace (never create a workspace inside the cloned git)
- Clone the git again in a new folder. to avoid merge conflicts
- Go to File->Import->Existing projects into workspace
- Browse to the git repository root folder
- Only import metricprocessor(.test), db, db.test, extractor, extractor.test, backend, backend.test
- First leave out the prototype please, because it can have a broken class path

Then import the projects, you will have errors in your projects because of the things I wrote before
Also I only had a ready mysql db, so I set up everything for mysql, feel free to change it to postgres, I will later install a postgresdb

A few notes to the Manifest file and the project itself:
- Keep it free from warnings, they are important. If you think you do everything right, supress the warning and write a comment why its ok
- Never edit the .classpath youself. If you have the feeling, you have to, write me, there is another way!
- Never use the Imported packages section of Manifest, use required plugins instead

This will make helping you much easier
